#!/bin/sh
cmp free42.h ../common/free42.h
cmp core_commands1.cpp ../common/core_commands1.cc
cmp core_commands1.h ../common/core_commands1.h
cmp core_commands2.cpp ../common/core_commands2.cc
cmp core_commands2.h ../common/core_commands2.h
cmp core_commands3.cpp ../common/core_commands3.cc
cmp core_commands3.h ../common/core_commands3.h
cmp core_commands4.cpp ../common/core_commands4.cc
cmp core_commands4.h ../common/core_commands4.h
cmp core_commands5.cpp ../common/core_commands5.cc
cmp core_commands5.h ../common/core_commands5.h
cmp core_commands6.cpp ../common/core_commands6.cc
cmp core_commands6.h ../common/core_commands6.h
cmp core_commands7.cpp ../common/core_commands7.cc
cmp core_commands7.h ../common/core_commands7.h
cmp core_commands8.cpp ../common/core_commands8.cc
cmp core_commands8.h ../common/core_commands8.h
cmp core_display.cpp ../common/core_display.cc
cmp core_display.h ../common/core_display.h
cmp core_globals.cpp ../common/core_globals.cc
cmp core_globals.h ../common/core_globals.h
cmp core_helpers.cpp ../common/core_helpers.cc
cmp core_helpers.h ../common/core_helpers.h
cmp core_keydown.cpp ../common/core_keydown.cc
cmp core_keydown.h ../common/core_keydown.h
cmp core_linalg1.cpp ../common/core_linalg1.cc
cmp core_linalg1.h ../common/core_linalg1.h
cmp core_linalg2.cpp ../common/core_linalg2.cc
cmp core_linalg2.h ../common/core_linalg2.h
cmp core_math1.cpp ../common/core_math1.cc
cmp core_math1.h ../common/core_math1.h
cmp core_math2.cpp ../common/core_math2.cc
cmp core_math2.h ../common/core_math2.h
cmp core_main.cpp ../common/core_main.cc
cmp core_main.h ../common/core_main.h
cmp core_phloat.cpp ../common/core_phloat.cc
cmp core_phloat.h ../common/core_phloat.h
cmp core_sto_rcl.cpp ../common/core_sto_rcl.cc
cmp core_sto_rcl.h ../common/core_sto_rcl.h
cmp core_tables.cpp ../common/core_tables.cc
cmp core_tables.h ../common/core_tables.h
cmp core_variables.cpp ../common/core_variables.cc
cmp core_variables.h ../common/core_variables.h
cmp FastDelegate.h ../common/FastDelegate.h
cmp hpil_common.cpp ../common/hpil_common.cc
cmp hpil_common.h ../common/hpil_common.h
cmp hpil_controller.cpp ../common/hpil_controller.cc
cmp hpil_controller.h ../common/hpil_controller.h
cmp hpil_core.cpp ../common/hpil_core.cc
cmp hpil_core.h ../common/hpil_core.h
cmp hpil_extended.cpp ../common/hpil_extended.cc
cmp hpil_extended.h ../common/hpil_extended.h
cmp hpil_mass.cpp ../common/hpil_mass.cc
cmp hpil_mass.h ../common/hpil_mass.h
cmp hpil_printer.cpp ../common/hpil_printer.cc
cmp hpil_printer.h ../common/hpil_printer.h
cmp hpil_plotter.cpp ../common/hpil_plotter.cc
cmp hpil_plotter.h ../common/hpil_plotter.h
cmp shell.h ../common/shell.h
cmp shell_loadimage.cpp ../common/shell_loadimage.cc
cmp shell_loadimage.h ../common/shell_loadimage.h
cmp shell_spool.cpp ../common/shell_spool.cc
cmp shell_spool.h ../common/shell_spool.h
cmp skin2cpp.cpp ../common/skin2cc.cc
cmp skin2cpp.conf ../common/skin2cc.conf
cmp keymap2cpp.cpp ../common/keymap2cc.cc
cmp bid_conf.h ../common/bid_conf.h
cmp bid_functions.h ../common/bid_functions.h
