#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define IDM_EXIT                                105
#define IDI_FREE42X                             106
#define IDI_FREE42                              107
#define IDI_HPIL                                108
#define IDI_SMALL                               109
#define IDC_FREE42                              110
#define IDD_PREFERENCES                         139
#define IDD_SELECTPROGRAM                       140
#define IDD_HPILPREFS                           142
#define IDD_ERROR                               144
#define IDC_MATRIX_SINGULARMATRIX               1000
#define IDC_MATRIX_OUTOFRANGE                   1001
#define IDC_AUTO_REPEAT                         1002
#define IDC_PRINTER_TXT                         1003
#define IDC_PRINTER_GIF                         1004
#define IDC_PRINTER_TXT_NAME                    1005
#define IDC_PRINTER_GIF_NAME                    1006
#define IDC_PRINTER_TXT_BROWSE                  1007
#define IDC_PRINTER_GIF_BROWSE                  1008
#define IDC_PRINTER_GIF_HEIGHT                  1010
#define IDC_LIST1                               1011
#define IDC_RAW_TEXT                            1013
#define IDC_ALWAYSONTOP                         1014
#define IDC_SINGLEINSTANCE                      1015
#define IDC_WEBSITELINK                         1017
#define IDC_FORUMLINK                           1018
#define IDC_XWEBSITELINK                        1019
#define IDM_SHOWPRINTOUT                        32771
#define IDM_CLEARPRINTOUT                       32772
#define IDM_PREFERENCES                         32773
#define IDM_EXPORTPROGRAM                       32774
#define IDM_IMPORTPROGRAM                       32775
#define ID_EDIT_COPY                            32777
#define ID_EDIT_PASTE                           32778
#define IDC_ERROR_TEXT                          40000
#define IDC_HPIL_HIGH_SPEED                     40000
#define IDM_HPILPREFS                           40000
#define IDS_APP_TITLE_BIN                       40000
#define IDC_HPIL_IP_ADD                         40001
#define IDS_APP_TITLE_DEC                       40001
#define IDC_HPIL_TCP_GRP                        40002
#define IDS_HELLO                               40002
#define IDC_FREE42_PRINTOUT                     40003
#define IDC_HPIL_TCP_PORT_OUT                   40003
#define IDC_HPIL_TCP_PORT_IN                    40004
#define IDS_PRINTOUT_TITLE                      40004
#define IDC_HPIL_LOW_SPEED                      40005
#define IDC_HPIL_INTERFACE                      40006
#define IDC_HPIL_SERIAL_GRP                     40007
#define IDC_HPIL_TCP_ADD_TXT                    40008
#define IDC_HPIL_TCP_OUTP_TXT                   40009
#define IDC_HPIL_TCP_INP_TXT                    40010
#define IDC_HPIL_MED_SPEED                      40011
#define IDC_HPIL_PIL_Box                        40012
