#!/bin/sh
cp bid_conf.h ../../common/bid_conf.h
cp bid_functions.h ../../common/bid_functions.h
cp core_commands1.cc ../../common/core_commands1.cc
cp core_commands1.h ../../common/core_commands1.h
cp core_commands2.cc ../../common/core_commands2.cc
cp core_commands2.h ../../common/core_commands2.h
cp core_commands3.cc ../../common/core_commands3.cc
cp core_commands3.h ../../common/core_commands3.h
cp core_commands4.cc ../../common/core_commands4.cc
cp core_commands4.h ../../common/core_commands4.h
cp core_commands5.cc ../../common/core_commands5.cc
cp core_commands5.h ../../common/core_commands5.h
cp core_commands6.cc ../../common/core_commands6.cc
cp core_commands6.h ../../common/core_commands6.h
cp core_commands7.cc ../../common/core_commands7.cc
cp core_commands7.h ../../common/core_commands7.h
cp core_commands8.cc ../../common/core_commands8.cc
cp core_commands8.h ../../common/core_commands8.h
cp core_display.cc ../../common/core_display.cc
cp core_display.h ../../common/core_display.h
cp core_globals.cc ../../common/core_globals.cc
cp core_globals.h ../../common/core_globals.h
cp core_helpers.cc ../../common/core_helpers.cc
cp core_helpers.h ../../common/core_helpers.h
cp core_keydown.cc ../../common/core_keydown.cc
cp core_keydown.h ../../common/core_keydown.h
cp core_linalg1.cc ../../common/core_linalg1.cc
cp core_linalg1.h ../../common/core_linalg1.h
cp core_linalg2.cc ../../common/core_linalg2.cc
cp core_linalg2.h ../../common/core_linalg2.h
cp core_main.cc ../../common/core_main.cc
cp core_main.h ../../common/core_main.h
cp core_math1.cc ../../common/core_math1.cc
cp core_math1.h ../../common/core_math1.h
cp core_math2.cc ../../common/core_math2.cc
cp core_math2.h ../../common/core_math2.h
cp core_phloat.cc ../../common/core_phloat.cc
cp core_phloat.h ../../common/core_phloat.h
cp core_sto_rcl.cc ../../common/core_sto_rcl.cc
cp core_sto_rcl.h ../../common/core_sto_rcl.h
cp core_tables.cc ../../common/core_tables.cc
cp core_tables.h ../../common/core_tables.h
cp core_variables.cc ../../common/core_variables.cc
cp core_variables.h ../../common/core_variables.h
cp free42.h ../../common/free42.h
cp FastDelegate.h ../../common/FastDelegate.h
cp hpil_common.cc ../../common/hpil_common.cc
cp hpil_common.h ../../common/hpil_common.h
cp hpil_controller.cc ../../common/hpil_controller.cc
cp hpil_controller.h ../../common/hpil_controller.h
cp hpil_core.cc ../../common/hpil_core.cc
cp hpil_core.h ../../common/hpil_core.h
cp hpil_extended.cc ../../common/hpil_extended.cc
cp hpil_extended.h ../../common/hpil_extended.h
cp hpil_mass.cc ../../common/hpil_mass.cc
cp hpil_mass.h ../../common/hpil_mass.h
cp hpil_plotter.cc ../../common/hpil_plotter.cc
cp hpil_plotter.h ../../common/hpil_plotter.h
cp hpil_printer.cc ../../common/hpil_printer.cc
cp hpil_printer.h ../../common/hpil_printer.h
cp shell.h ../../common/shell.h
cp shell_spool.cc ../../common/shell_spool.cc
cp shell_spool.h ../../common/shell_spool.h
